#include "ui.h"

void ui_init() {
	//Score Box
		//Box
		UI_SCORE_BOX_POSITION.x = 7 * SCR_WIDTH / 8.0;
		UI_SCORE_BOX_POSITION.y = 7 * SCR_HEIGHT / 10.0;

		UI_SCORE_BOX_SCALE.x = SCR_WIDTH / 5.0;
		UI_SCORE_BOX_SCALE.y = SCR_HEIGHT / 2.0;

		//Title
		unsigned int UI_SCORE_TITLE_TEXT_LENGTH = 0;

		for (unsigned char* c = UI_SCORE_TITLE_TEXT; *c != TP_NULL; c++, UI_SCORE_TITLE_TEXT_LENGTH++) {}

		UI_SCORE_TITLE_TEXT_POSITION.x = UI_SCORE_BOX_POSITION.x;
		UI_SCORE_TITLE_TEXT_POSITION.y = UI_SCORE_BOX_POSITION.y - 3 * UI_SCORE_BOX_SCALE.y / 8.0;

		UI_SCORE_TITLE_TEXT_SCALE.x = (3 * UI_SCORE_BOX_SCALE.x) / (4.0 * UI_SCORE_TITLE_TEXT_LENGTH) - ((UI_SCORE_TITLE_TEXT_LENGTH - 1) * UI_TEXT_CHAR_SPACING) / (float)UI_SCORE_TITLE_TEXT_LENGTH;
		UI_SCORE_TITLE_TEXT_SCALE.y = UI_TEXT_HEIGHT;

		//Score
		for (unsigned char i = 0; i < UI_GAME_SCORE_TEXT_LENGTH; i++)
			UI_GAME_SCORE_TEXT[i] = '0';
		UI_GAME_SCORE_TEXT[UI_GAME_SCORE_TEXT_LENGTH] = '\0';

		UI_SCORE_TEXT_POSITION.x = UI_SCORE_BOX_POSITION.x;
		UI_SCORE_TEXT_POSITION.y = UI_SCORE_BOX_POSITION.y;

		UI_SCORE_TEXT_SCALE.x = (3 * UI_SCORE_BOX_SCALE.x) / (4.0 * UI_GAME_SCORE_TEXT_LENGTH) - ((UI_GAME_SCORE_TEXT_LENGTH - 1) * UI_TEXT_CHAR_SPACING) / (float)UI_GAME_SCORE_TEXT_LENGTH;
		UI_SCORE_TEXT_SCALE.y = UI_TEXT_HEIGHT;

	//Next Box
		//Box
		UI_NEXT_BOX_POSITION.x = 7 * SCR_WIDTH / 8.0;
		UI_NEXT_BOX_POSITION.y = 9 * SCR_HEIGHT / 40.0;

		UI_NEXT_BOX_SCALE.x = SCR_WIDTH / 5.0;
		UI_NEXT_BOX_SCALE.y = 7 * SCR_HEIGHT / 20.0;

		//Title
		unsigned int UI_NEXT_TITLE_TEXT_LENGTH = 0;

		for (unsigned char* c = UI_NEXT_TITLE_TEXT; *c != TP_NULL; c++, UI_NEXT_TITLE_TEXT_LENGTH++) {}

		UI_NEXT_TITLE_TEXT_POSITION.x = UI_NEXT_BOX_POSITION.x;
		UI_NEXT_TITLE_TEXT_POSITION.y = UI_NEXT_BOX_POSITION.y - UI_NEXT_BOX_SCALE.y / 4.0;

		UI_NEXT_TITLE_TEXT_SCALE.x = (3 * UI_NEXT_BOX_SCALE.x) / (4.0 * UI_NEXT_TITLE_TEXT_LENGTH) - ((UI_NEXT_TITLE_TEXT_LENGTH - 1) * UI_TEXT_CHAR_SPACING) / (float)UI_NEXT_TITLE_TEXT_LENGTH;
		UI_NEXT_TITLE_TEXT_SCALE.y = UI_TEXT_HEIGHT;

		//Piece

	//Hold Box
		//Box
		UI_HOLD_BOX_POSITION.x = SCR_WIDTH / 8.0;
		UI_HOLD_BOX_POSITION.y = 9 * SCR_HEIGHT / 40.0;

		UI_HOLD_BOX_SCALE.x = SCR_WIDTH / 5.0;
		UI_HOLD_BOX_SCALE.y = 7 * SCR_HEIGHT / 20.0;

		//Title
		unsigned int UI_HOLD_TITLE_TEXT_LENGTH = 0;

		for (unsigned char* c = UI_HOLD_TITLE_TEXT; *c != TP_NULL; c++, UI_HOLD_TITLE_TEXT_LENGTH++) {}

		UI_HOLD_TITLE_TEXT_POSITION.x = UI_HOLD_BOX_POSITION.x;
		UI_HOLD_TITLE_TEXT_POSITION.y = UI_HOLD_BOX_POSITION.y - UI_HOLD_BOX_SCALE.y / 4.0;

		UI_HOLD_TITLE_TEXT_SCALE.x = (3 * UI_HOLD_BOX_SCALE.x) / (4.0 * UI_NEXT_TITLE_TEXT_LENGTH) - ((UI_NEXT_TITLE_TEXT_LENGTH - 1) * UI_TEXT_CHAR_SPACING) / (float)UI_NEXT_TITLE_TEXT_LENGTH;
		UI_HOLD_TITLE_TEXT_SCALE.y = UI_TEXT_HEIGHT;

		//Piece

	//Stats Box
		//Box
		UI_STATS_BOX_POSITION.x = SCR_WIDTH / 8.0;
		UI_STATS_BOX_POSITION.y = 7 * SCR_HEIGHT / 10.0;

		UI_STATS_BOX_SCALE.x = SCR_WIDTH / 5.0;
		UI_STATS_BOX_SCALE.y = SCR_HEIGHT / 2.0;

		//Title
		unsigned int G_GAME_STATS_TITLE_TEXT_LENGTH = 0;

		for (unsigned char* c = UI_STATS_TITLE_TEXT; *c != TP_NULL; c++ < G_GAME_STATS_TITLE_TEXT_LENGTH++) {}

		UI_STATS_TITLE_TEXT_POSITION.x = UI_STATS_BOX_POSITION.x;
		UI_STATS_TITLE_TEXT_POSITION.y = UI_STATS_BOX_POSITION.y - 3 * UI_STATS_BOX_SCALE.y / 8.0;

		UI_STATS_TITLE_TEXT_SCALE.x = (3 * UI_STATS_BOX_SCALE.x) / (4.0 * G_GAME_STATS_TITLE_TEXT_LENGTH) - ((G_GAME_STATS_TITLE_TEXT_LENGTH - 1) * UI_TEXT_CHAR_SPACING) / (float)G_GAME_STATS_TITLE_TEXT_LENGTH;
		UI_STATS_TITLE_TEXT_SCALE.y = UI_TEXT_HEIGHT;

		//Elements
		for (unsigned int i = 0; i < UI_STATS_NUM_LENGTH; i++) {
			UI_STATS_I_BLOCK_TEXT[i] = '0';
			UI_STATS_J_BLOCK_TEXT[i] = '0';
			UI_STATS_L_BLOCK_TEXT[i] = '0';
			UI_STATS_O_BLOCK_TEXT[i] = '0';
			UI_STATS_S_BLOCK_TEXT[i] = '0';
			UI_STATS_T_BLOCK_TEXT[i] = '0';
			UI_STATS_Z_BLOCK_TEXT[i] = '0';
		}
		UI_STATS_I_BLOCK_TEXT[UI_STATS_NUM_LENGTH] = '\0';
		UI_STATS_J_BLOCK_TEXT[UI_STATS_NUM_LENGTH] = '\0';
		UI_STATS_L_BLOCK_TEXT[UI_STATS_NUM_LENGTH] = '\0';
		UI_STATS_O_BLOCK_TEXT[UI_STATS_NUM_LENGTH] = '\0';
		UI_STATS_S_BLOCK_TEXT[UI_STATS_NUM_LENGTH] = '\0';
		UI_STATS_T_BLOCK_TEXT[UI_STATS_NUM_LENGTH] = '\0';
		UI_STATS_Z_BLOCK_TEXT[UI_STATS_NUM_LENGTH] = '\0';

		UI_STATS_ELEMENT_TEXT_CHAR_SCALE.x = (9 * UI_STATS_ELEMENT_SCALE.x) / (float)(20 * UI_STATS_NUM_LENGTH) - ((UI_STATS_NUM_LENGTH - 1) * UI_TEXT_CHAR_SPACING) / (float)UI_STATS_NUM_LENGTH;
		UI_STATS_ELEMENT_TEXT_CHAR_SCALE.y = (3 * UI_STATS_ELEMENT_SCALE.y) / 4.0;

		UI_STATS_ELEMENT_BLOCK_SIZE = (2 * UI_STATS_ELEMENT_SCALE.x / (float)5) / (float)4;

		//I Block
		UI_STATS_I_ELEMENT_TEXT_POSITION.x = UI_STATS_BOX_POSITION.x + UI_STATS_ELEMENT_SCALE.x / 5.0;
		UI_STATS_I_ELEMENT_TEXT_POSITION.y = UI_STATS_BOX_POSITION.y + UI_STATS_BOX_SCALE.y / 16.0 - (9 * UI_STATS_ELEMENT_SCALE.y) / 2.0 - 3 * UI_STATS_ELEMENT_SPACING;

		UI_STATS_I_ELEMENT_BLOCK_POSITION.x = UI_STATS_BOX_POSITION.x - (3 * UI_STATS_ELEMENT_SCALE.x / (float)10);
		UI_STATS_I_ELEMENT_BLOCK_POSITION.y = UI_STATS_I_ELEMENT_TEXT_POSITION.y;

		//J Block
		UI_STATS_J_ELEMENT_TEXT_POSITION.x = UI_STATS_BOX_POSITION.x + UI_STATS_ELEMENT_SCALE.x / 5.0;
		UI_STATS_J_ELEMENT_TEXT_POSITION.y = UI_STATS_BOX_POSITION.y + UI_STATS_BOX_SCALE.y / 16.0 - (6 * UI_STATS_ELEMENT_SCALE.y) / 2.0 - 2 * UI_STATS_ELEMENT_SPACING;

		UI_STATS_J_ELEMENT_BLOCK_POSITION.x = UI_STATS_BOX_POSITION.x - (3 * UI_STATS_ELEMENT_SCALE.x / (float)10);
		UI_STATS_J_ELEMENT_BLOCK_POSITION.y = UI_STATS_J_ELEMENT_TEXT_POSITION.y;

		//L Block
		UI_STATS_L_ELEMENT_TEXT_POSITION.x = UI_STATS_BOX_POSITION.x + UI_STATS_ELEMENT_SCALE.x / 5.0;
		UI_STATS_L_ELEMENT_TEXT_POSITION.y = UI_STATS_BOX_POSITION.y + UI_STATS_BOX_SCALE.y / 16.0 - (3 * UI_STATS_ELEMENT_SCALE.y) / 2.0 - UI_STATS_ELEMENT_SPACING;

		UI_STATS_L_ELEMENT_BLOCK_POSITION.x = UI_STATS_BOX_POSITION.x - (3 * UI_STATS_ELEMENT_SCALE.x / (float)10);
		UI_STATS_L_ELEMENT_BLOCK_POSITION.y = UI_STATS_L_ELEMENT_TEXT_POSITION.y;

		//O Block
		UI_STATS_O_ELEMENT_TEXT_POSITION.x = UI_STATS_BOX_POSITION.x + UI_STATS_ELEMENT_SCALE.x / 5.0;
		UI_STATS_O_ELEMENT_TEXT_POSITION.y = UI_STATS_BOX_POSITION.y + UI_STATS_BOX_SCALE.y / 16.0;

		UI_STATS_O_ELEMENT_BLOCK_POSITION.x = UI_STATS_BOX_POSITION.x - (3 * UI_STATS_ELEMENT_SCALE.x / (float)10);
		UI_STATS_O_ELEMENT_BLOCK_POSITION.y = UI_STATS_O_ELEMENT_TEXT_POSITION.y;

		//S Block
		UI_STATS_S_ELEMENT_TEXT_POSITION.x = UI_STATS_BOX_POSITION.x + UI_STATS_ELEMENT_SCALE.x / 5.0;
		UI_STATS_S_ELEMENT_TEXT_POSITION.y = UI_STATS_BOX_POSITION.y + UI_STATS_BOX_SCALE.y / 16.0 + (3 * UI_STATS_ELEMENT_SCALE.y) / 2.0 + UI_STATS_ELEMENT_SPACING;

		UI_STATS_S_ELEMENT_BLOCK_POSITION.x = UI_STATS_BOX_POSITION.x - (3 * UI_STATS_ELEMENT_SCALE.x / (float)10);
		UI_STATS_S_ELEMENT_BLOCK_POSITION.y = UI_STATS_S_ELEMENT_TEXT_POSITION.y;

		//T Block
		UI_STATS_T_ELEMENT_TEXT_POSITION.x = UI_STATS_BOX_POSITION.x + UI_STATS_ELEMENT_SCALE.x / 5.0;
		UI_STATS_T_ELEMENT_TEXT_POSITION.y = UI_STATS_BOX_POSITION.y + UI_STATS_BOX_SCALE.y / 16.0 + (6 * UI_STATS_ELEMENT_SCALE.y) / 2.0 + 2 * UI_STATS_ELEMENT_SPACING;

		UI_STATS_T_ELEMENT_BLOCK_POSITION.x = UI_STATS_BOX_POSITION.x - (3 * UI_STATS_ELEMENT_SCALE.x / (float)10);
		UI_STATS_T_ELEMENT_BLOCK_POSITION.y = UI_STATS_T_ELEMENT_TEXT_POSITION.y;

		//Z Block
		UI_STATS_Z_ELEMENT_TEXT_POSITION.x = UI_STATS_BOX_POSITION.x + UI_STATS_ELEMENT_SCALE.x / 5.0;
		UI_STATS_Z_ELEMENT_TEXT_POSITION.y = UI_STATS_BOX_POSITION.y + UI_STATS_BOX_SCALE.y / 16.0 + (9 * UI_STATS_ELEMENT_SCALE.y) / 2.0 + 3 * UI_STATS_ELEMENT_SPACING;

		UI_STATS_Z_ELEMENT_BLOCK_POSITION.x = UI_STATS_BOX_POSITION.x - (3 * UI_STATS_ELEMENT_SCALE.x / (float)10);
		UI_STATS_Z_ELEMENT_BLOCK_POSITION.y = UI_STATS_Z_ELEMENT_TEXT_POSITION.y;
}

void ui_render() {
	//Score
	qd_drawOutlineRect(UI_SCORE_BOX_POSITION, UI_SCORE_BOX_SCALE, UI_BOX_THICKNESS, COLOR_WHITE);

	tp_drawString(UI_SCORE_TITLE_TEXT_POSITION, UI_SCORE_TITLE_TEXT_SCALE, COLOR_WHITE, UI_TEXT_THICKNESS_BOLD, UI_TEXT_CHAR_SPACING, TP_NO_SPACING, TP_ALIGNMENT_CENTER, UI_SCORE_TITLE_TEXT);
	tp_drawString(UI_SCORE_TEXT_POSITION, UI_SCORE_TEXT_SCALE, COLOR_WHITE, UI_TEXT_THICKNESS_STANDARD, UI_TEXT_CHAR_SPACING, TP_NO_SPACING, TP_ALIGNMENT_CENTER, UI_GAME_SCORE_TEXT);

	//Next
	qd_drawOutlineRect(UI_NEXT_BOX_POSITION, UI_NEXT_BOX_SCALE, UI_BOX_THICKNESS, COLOR_WHITE);

	tp_drawString(UI_NEXT_TITLE_TEXT_POSITION, UI_NEXT_TITLE_TEXT_SCALE, COLOR_WHITE, UI_TEXT_THICKNESS_BOLD, UI_TEXT_CHAR_SPACING, TP_NO_SPACING, TP_ALIGNMENT_CENTER, UI_NEXT_TITLE_TEXT);

	//Hold
	qd_drawOutlineRect(UI_HOLD_BOX_POSITION, UI_HOLD_BOX_SCALE, UI_BOX_THICKNESS, COLOR_WHITE);

	tp_drawString(UI_HOLD_TITLE_TEXT_POSITION, UI_HOLD_TITLE_TEXT_SCALE, COLOR_WHITE, UI_TEXT_THICKNESS_BOLD, UI_TEXT_CHAR_SPACING, TP_NO_SPACING, TP_ALIGNMENT_CENTER, UI_HOLD_TITLE_TEXT);

	//Stats
	qd_drawOutlineRect(UI_STATS_BOX_POSITION, UI_STATS_BOX_SCALE, UI_BOX_THICKNESS, COLOR_WHITE);

	tp_drawString(UI_STATS_TITLE_TEXT_POSITION, UI_STATS_TITLE_TEXT_SCALE, COLOR_WHITE, UI_TEXT_THICKNESS_BOLD, UI_TEXT_CHAR_SPACING, TP_NO_SPACING, TP_ALIGNMENT_CENTER, UI_STATS_TITLE_TEXT);

	//I
	tp_drawString(UI_STATS_I_ELEMENT_TEXT_POSITION, UI_STATS_ELEMENT_TEXT_CHAR_SCALE, COLOR_WHITE, UI_TEXT_THICKNESS_STANDARD, UI_TEXT_CHAR_SPACING, TP_NO_SPACING, TP_ALIGNMENT_CENTER, UI_STATS_I_BLOCK_TEXT);
	p_drawDummy(P_I_PIECE_INDEX, &UI_STATS_I_ELEMENT_BLOCK_POSITION, UI_STATS_ELEMENT_BLOCK_SIZE, COLOR_INDEX_BLUE);

	//J
	tp_drawString(UI_STATS_J_ELEMENT_TEXT_POSITION, UI_STATS_ELEMENT_TEXT_CHAR_SCALE, COLOR_WHITE, UI_TEXT_THICKNESS_STANDARD, UI_TEXT_CHAR_SPACING, TP_NO_SPACING, TP_ALIGNMENT_CENTER, UI_STATS_J_BLOCK_TEXT);
	p_drawDummy(P_J_PIECE_INDEX, &UI_STATS_J_ELEMENT_BLOCK_POSITION, UI_STATS_ELEMENT_BLOCK_SIZE, COLOR_INDEX_TEAL);

	//L
	tp_drawString(UI_STATS_L_ELEMENT_TEXT_POSITION, UI_STATS_ELEMENT_TEXT_CHAR_SCALE, COLOR_WHITE, UI_TEXT_THICKNESS_STANDARD, UI_TEXT_CHAR_SPACING, TP_NO_SPACING, TP_ALIGNMENT_CENTER, UI_STATS_L_BLOCK_TEXT);
	p_drawDummy(P_L_PIECE_INDEX, &UI_STATS_L_ELEMENT_BLOCK_POSITION, UI_STATS_ELEMENT_BLOCK_SIZE, COLOR_INDEX_ORANGE);

	//O
	tp_drawString(UI_STATS_O_ELEMENT_TEXT_POSITION, UI_STATS_ELEMENT_TEXT_CHAR_SCALE, COLOR_WHITE, UI_TEXT_THICKNESS_STANDARD, UI_TEXT_CHAR_SPACING, TP_NO_SPACING, TP_ALIGNMENT_CENTER, UI_STATS_O_BLOCK_TEXT);
	p_drawDummy(P_O_PIECE_INDEX, &UI_STATS_O_ELEMENT_BLOCK_POSITION, UI_STATS_ELEMENT_BLOCK_SIZE, COLOR_INDEX_YELLOW);

	//S
	tp_drawString(UI_STATS_S_ELEMENT_TEXT_POSITION, UI_STATS_ELEMENT_TEXT_CHAR_SCALE, COLOR_WHITE, UI_TEXT_THICKNESS_STANDARD, UI_TEXT_CHAR_SPACING, TP_NO_SPACING, TP_ALIGNMENT_CENTER, UI_STATS_S_BLOCK_TEXT);
	p_drawDummy(P_S_PIECE_INDEX, &UI_STATS_S_ELEMENT_BLOCK_POSITION, UI_STATS_ELEMENT_BLOCK_SIZE, COLOR_INDEX_RED);

	//T
	tp_drawString(UI_STATS_T_ELEMENT_TEXT_POSITION, UI_STATS_ELEMENT_TEXT_CHAR_SCALE, COLOR_WHITE, UI_TEXT_THICKNESS_STANDARD, UI_TEXT_CHAR_SPACING, TP_NO_SPACING, TP_ALIGNMENT_CENTER, UI_STATS_T_BLOCK_TEXT);
	p_drawDummy(P_T_PIECE_INDEX, &UI_STATS_T_ELEMENT_BLOCK_POSITION, UI_STATS_ELEMENT_BLOCK_SIZE, COLOR_INDEX_PURPLE);

	//Z
	tp_drawString(UI_STATS_Z_ELEMENT_TEXT_POSITION, UI_STATS_ELEMENT_TEXT_CHAR_SCALE, COLOR_WHITE, UI_TEXT_THICKNESS_STANDARD, UI_TEXT_CHAR_SPACING, TP_NO_SPACING, TP_ALIGNMENT_CENTER, UI_STATS_Z_BLOCK_TEXT);
	p_drawDummy(P_Z_PIECE_INDEX, &UI_STATS_Z_ELEMENT_BLOCK_POSITION, UI_STATS_ELEMENT_BLOCK_SIZE, COLOR_INDEX_GREEN);
}

void ui_updateScoreText(unsigned int score) {
	for (short i = UI_GAME_SCORE_TEXT_LENGTH - 1; i >= 0; i--) {
		unsigned int digit;

		digit = score % 10;

		UI_GAME_SCORE_TEXT[i] = digit + '0';

		score /= 10;
	}
}

void ui_updateStatsText(unsigned char blockType, unsigned short newStat) {
	char* text;

	switch (blockType) {
	case P_I_PIECE_INDEX:
		text = UI_STATS_I_BLOCK_TEXT;

		break;
	case P_J_PIECE_INDEX:
		text = UI_STATS_J_BLOCK_TEXT;

		break;
	case P_L_PIECE_INDEX:
		text = UI_STATS_L_BLOCK_TEXT;

		break;
	case P_O_PIECE_INDEX:
		text = UI_STATS_O_BLOCK_TEXT;

		break;
	case P_S_PIECE_INDEX:
		text = UI_STATS_S_BLOCK_TEXT;

		break;
	case P_T_PIECE_INDEX:
		text = UI_STATS_T_BLOCK_TEXT;

		break;
	case P_Z_PIECE_INDEX:
		text = UI_STATS_Z_BLOCK_TEXT;

		break;
	default:
		printf("WARNING: invalid block type passed to ui_updateStatsText\n");
		return;
	}

	for (int i = UI_STATS_NUM_LENGTH - 1; i >= 0; i--) {
		unsigned short digit;

		digit = newStat % 10;

		text[i] = digit + '0';

		newStat /= 10;
	}
}
